In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [8]:
print(arr[1:5:2])

[2 4]


In [9]:
import numpy as np

In [12]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [13]:
print(arr[1, 1:4])

[7 8 9]


In [14]:
import numpy as np

In [15]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a[1:5]

array([2, 3, 4, 5])

In [17]:
a[2:7]

array([3, 4, 5, 6, 7])

In [18]:
a[0:5]

array([1, 2, 3, 4, 5])

In [19]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [20]:
a[1:6:2]

array([2, 4, 6])

#SLICE a 2D Array

In [21]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [22]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
b[1, 1:14]

array([ 7,  8,  9, 10])

In [24]:
b[0, 0:3]

array([1, 2, 3])