In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [3]:
x = np.where(arr == 4)

In [4]:
print(x)

(array([3, 5, 6], dtype=int64),)


In [5]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
x = np.where(arr%2 == 0)

In [8]:
print(x)

(array([1, 3, 5, 7], dtype=int64),)


#SORT THE ARRAY

In [9]:
import numpy as np

In [10]:
arr = np.array([3, 2, 0, 1])

In [11]:
print(np.sort(arr))

[0 1 2 3]


In [12]:
import numpy as np

In [13]:
arr = np.array(['banana', 'cherry', 'apple'])

In [14]:
print(np.sort(arr))

['apple' 'banana' 'cherry']


#Lets Begin

In [16]:
import numpy as np

In [17]:
a = np.array ([1,  2, 3, 3, 4, 5, 6, 5, 10, 20, 1])

In [18]:
x = np.where(a == 1)

In [19]:
x

(array([ 0, 10], dtype=int64),)

In [21]:
y = np.where(a == 4)

In [22]:
y

(array([4], dtype=int64),)

In [25]:
ans = np.where(a%2 == 0)

In [26]:
ans

(array([1, 4, 6, 8, 9], dtype=int64),)

In [27]:
np.sort (a)

array([ 1,  1,  2,  3,  3,  4,  5,  5,  6, 10, 20])

In [28]:
a2 = np.array([44, 12, 90, 77, 55])

In [29]:
np.sort (a2)

array([12, 44, 55, 77, 90])

In [30]:
a3 = np.array(['apel', 'pisang', 'anggur', 'melon', 'nangka'])

In [31]:
np.sort (a3)

array(['anggur', 'apel', 'melon', 'nangka', 'pisang'], dtype='<U6')