In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
x = 5

In [3]:
name = 'seno'

In [4]:
print (name)

seno


In [8]:
import numpy as np

arr= np.array([1,2,3])

print(arr)

type(arr)

[1 2 3]


numpy.ndarray

In [9]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [11]:
import numpy as np
arr = np.array([[42], [71]])
print(arr)

[[42]
 [71]]


In [3]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3,], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Zero D Arrai

In [1]:
import numpy as np

In [2]:
a = np.array(55)

In [4]:
a

array(42)

In [5]:
type(a)

numpy.ndarray

In [6]:
a.ndim

0

In [7]:
b = np.array ([1, 2, 3, 4, 5])

In [8]:
b

array([1, 2, 3, 4, 5])

In [9]:
b.ndim

1

# 2D Array

In [10]:
c = np.array ([[1, 2, 3,], [4, 5, 6]])

In [11]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
c.ndim

2

#3d Array

In [14]:
d = np.array([1,2,3],[4,5,6][[1,2,3],[4,5,6]])

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\SENO D\AppData\Local\Temp\ipykernel_19040\571698458.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  d = np.array([1,2,3],[4,5,6][[1,2,3],[4,5,6]])
C:\Users\SENO D\AppData\Local\Temp\ipykernel_19040\571698458.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  d = np.array([1,2,3],[4,5,6][[1,2,3],[4,5,6]])
C:\Users\SENO D\AppData\Local\Temp\ipykernel_19040\571698458.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  d = np.array([1,2,3],[4,5,6][[1,2,3],[4,5,6]])


TypeError: list indices must be integers or slices, not tuple

In [15]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [16]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [17]:
d.ndim

3