In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [3]:
print(arr.shape)

(2, 4)


In [4]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [6]:
newarr = arr.reshape(4, 3)

In [7]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
import numpy as np

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [10]:
newarr = arr.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [11]:
newarr = arr.reshape(6, 2)

In [12]:
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [14]:
newarr = arr.reshape(-1)

In [15]:
print(newarr)

[1 2 3 4 5 6]


In [16]:
import numpy as np

In [17]:
a = np.array([1, 2, 3, 4, 5])

In [18]:
a.shape

(5,)

In [19]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [20]:
b.shape

(2, 4)

In [21]:
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [22]:
new_arr = c.reshape(4,3)

In [23]:
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
new_arr.shape

(4, 3)

In [25]:
new_arr2 = c.reshape(2,3,2)

In [26]:
new_arr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [27]:
new_arr2.shape

(2, 3, 2)

In [28]:
twoD_array = np.array([[1, 2, 3], [4, 5, 6]])

In [29]:
flatten_array = twoD_array.reshape(-1)

In [30]:
flatten_array

array([1, 2, 3, 4, 5, 6])

In [31]:
flatten_array.shape

(6,)